// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThk5xLnGv9-ZYmXOJLc1jvS1ihF68OvA',
    appId: '1:839042477667:web:d56291ab04584e7c5ad256',
    messagingSenderId: '839042477667',
    projectId: 'gestion-commerce-reparation',
    authDomain: 'gestion-commerce-reparation.firebaseapp.com',
    storageBucket: 'gestion-commerce-reparation.appspot.com',
    measurementId: 'G-T16E7MKLCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_944x9-bStuHH4x4FqFYRsDJsJwJGEoA',
    appId: '1:839042477667:android:9791fa10e041b9125ad256',
    messagingSenderId: '839042477667',
    projectId: 'gestion-commerce-reparation',
    storageBucket: 'gestion-commerce-reparation.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAThk5xLnGv9-ZYmXOJLc1jvS1ihF68OvA',
    appId: '1:839042477667:web:25a30c371acb0a8f5ad256',
    messagingSenderId: '839042477667',
    projectId: 'gestion-commerce-reparation',
    authDomain: 'gestion-commerce-reparation.firebaseapp.com',
    storageBucket: 'gestion-commerce-reparation.appspot.com',
    measurementId: 'G-MN72V96QZE',
  );

}